language: python
sudo: required
python:
  - "3.6"
services:
  - mysql
  - redis-server
notifications:
  email: false
cache:
  pip: true
  directories:
    - tmp
install: "bash .travis-install"
script: "biohub/manage.py test && TEST_ABACUS=1 biohub/manage.py test abacus"
